### ISSUE TITLE
Running the verifier locally in Docker

### ISSUE THREAD

**Issue by esune** [CQEN-QDCE/exp-verifier-voyages#1]
I could not find a docker-compose and/or instructions in the repository: it would be nice to be able to run everything locally before it is deployed to a cloud platform.

Note: the agent endpoint must be publicly addressable from the Internet, an option to achieve this could be by using `ngrok`.

**Comment by torjc01** [comment]
La solution d'exécution du projet integrée est deployée avec le PR dans le répo bcgov/dts-vc-issuer-service#67. 

The solution for the integrated lauche was deployed with bcgov/dts-vc-issuer-service#67 PR.
