### ISSUE TITLE
Retirer le code non utilisé / Clean old code base

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#10]

**Comment by torjc01** [comment]
Le code non utilisé a été épuré et supprimé; les références non utilisées ont aussi été épurées.

**Comment by torjc01** [comment]
@flihp27  Phillipe, merci de réviser cet issue. Il est prêt à être fermé.

**Comment by torjc01** [comment]
Activité finie, on passe à la fermeture de l'issue.
