### ISSUE TITLE
Transférer le repo à un répertoire dans le repo du BC / Transfert repo to a dir in BC repo

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#13]
Transfert this repo to a dir called "verifier" in the BC issuer repo that we are collaborating together https://github.com/bcgov/dts-vc-issuer-service.

**Comment by torjc01** [comment]
Transfert du repo au BC demandé le 28/04. en attende de l'approbation par leur reviwer.

**Comment by torjc01** [comment]
Le transfert a été fait avec le PR dans le répo bcgov/dts-vc-issuer-service#67.

The transfer was deployed with bcgov/dts-vc-issuer-service#67 PR.
