### ISSUE TITLE
Ajouter la license du Qúebec au repo du BC pour les parties contribués et signés par les employés du QC / Add Qc License to BC repo for the parts contributed and signed by Qc employes

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#14]
- Include Quebec open source license to the common project with BC
Should be easy, since the Qc license is a reciprocity license.

**Comment by torjc01** [comment]
Stephen Curran dans le PR du repo du BC nous interpelle sur la license du Québec. Je le cite:

**Comment by torjc01** [comment]
"
"I'm concerned about the license to be used for this. Everything in Hyperledger/Linux Foundation is licensed under the Apache 2 license, and if this work moves anywhere, this licensing could cause an issue. As well, having a single repo with multiple licenses is not a good idea.

Would it be possible to change this to use Apache 2 licensing for this work?"

**Comment by flihp27** [comment]
Nous avons décidés de conserver la licence ouverte de la Linux Foundation.
