### ISSUE TITLE
Preuve sans connection / Connectionless proof

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#5]
Change the invitation QR to use connection-less proof.

**Comment by torjc01** [comment]
Le modèle de base pour la transaction connectionless à utiliser appartient au projet exp-vc-authn-oidc (https://github.com/CQEN-QDCE/exp-vc-authn-oidc).

**Comment by torjc01** [comment]
Modèle de la présentation de preuve à partir d'ACA-PY: 
https://ldej.nl/post/becoming-a-hyperledger-aries-developer-part-7-present-proof/
