### ISSUE TITLE
Ajouter liste de cred def de confiance / Add array of trusted cred def

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#6]
code ex:							"restrictions": [
									{
									"cred_def_id": cred_def_id
									},
									{
										"cred_def_id": cred_def_id
									}
								]
Include by a parameter file.

**Comment by torjc01** [comment]
Au lieu d'ajouter comme restriction les `cred_def_id`, on a mis la restriction `schema_name` et `schema_id`, qui est plus général et plus performant. 

Instead of restricting by `cred_def_id`, we have restricted by `schema_name` and `schema_id`, which are more general and performant.
