### ISSUE TITLE
Traduire les "README" / Translate the README files

### ISSUE THREAD

**Issue by flihp27** [CQEN-QDCE/exp-verifier-voyages#8]
Offrir des explications autant en français qu'en anglais pour que ce soit ouvert.

**Comment by torjc01** [comment]
Martin, voici l'issue de la traduction. Je pense qu'elle est pas mal terminé. Fais un review, stp?

**Comment by torjc01** [comment]
Activité finie, on passe à la fermeture de l'issue.
